"""int8 TFLite export for TFLite Micro + a reference interpreter run."""
import os

import numpy as np
import tensorflow as tf


def int8(model, rep, out_dir, name):
    """Full-integer quantise; writes <name>_int8.tflite and <name>_data.h (C array)."""
    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = lambda: ([r[None]] for r in rep)
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    blob = conv.convert()
    path = os.path.join(out_dir, f"{name}_int8.tflite")
    with open(path, "wb") as f:
        f.write(blob)
    with open(os.path.join(out_dir, f"{name}_data.h"), "w") as f:
        f.write("// Generated by handwritten_sum/export.py - do not edit.\n#pragma once\n#include <stdint.h>\n\n")
        f.write(f"alignas(16) const unsigned char g_{name}[] = {{\n")
        for i in range(0, len(blob), 16):
            f.write("  " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) + ",\n")
        f.write(f"}};\nconst unsigned int g_{name}_len = {len(blob)};\n")
    return path, len(blob)


def predict(path, X):
    """Run the int8 .tflite exactly as the MCU would; returns float softmax over the last axis."""
    it = tf.lite.Interpreter(model_path=path)
    it.allocate_tensors()
    inp, out = it.get_input_details()[0], it.get_output_details()[0]
    si, zi = inp["quantization"]
    so, zo = out["quantization"]
    res = []
    for x in X:
        it.set_tensor(inp["index"], np.clip(np.round(x / si + zi), -128, 127).astype(np.int8)[None])
        it.invoke()
        logits = (it.get_tensor(out["index"])[0].astype(np.float32) - zo) * so
        e = np.exp(logits - logits.max(-1, keepdims=True))
        res.append(e / e.sum(-1, keepdims=True))
    return np.array(res)
